- name: remove mysql
  hosts: mysql-server
  user: root
  gather_facts: false
  vars:
  - prefix: "/usr/local"
    user: "mysql"
  tasks:
  - name: remove_server
    script: "../script/mysql_remove.sh -u {{user}} -f {{prefix}} -c /etc/my.cnf"
