- name: remove redis
  hosts: redis-server
  user: root
  gather_facts: false
  vars:
  - prefix: "/usr/local"
    user: "redis"
  tasks:
  - name: remove_server
    script: "../script/redis_remove.sh -u {{user}} -f {{prefix}}"
